// ATLMFC build numbers (YYMMDD)
#pragma once
 
#define _LIBS_BUILD 51106
#define _LIBS_USER_BUILD "51106"
 
#define _LIBS_PRODUCT_VERSION_MAJOR 11
#define _LIBS_USER_PRODUCT_VERSION_MAJOR "11"
#define _LIBS_PRODUCT_VERSION_MINOR 0
#define _LIBS_USER_PRODUCT_VERSION_MINOR "00"
 
#define _LIBS_FILE_VERSION_MAJOR 11
#define _LIBS_USER_FILE_VERSION_MAJOR "11"
#define _LIBS_FILE_VERSION_MINOR 0
#define _LIBS_USER_FILE_VERSION_MINOR "00"
#define _LIBS_USER_FULL_VER "11.00.51106"
 
#ifndef _LIBS_RBLD
#define _LIBS_RBLD 1
#define _LIBS_USER_RBLD "01"
#endif
